//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases
    {
        public int id { get; set; }
        public string email { get; set; }
        public int idProduct { get; set; }
        public string productName { get; set; }

        public Purchases(string email, int idProduct, string productName)
        {
            this.email = email;
            this.idProduct = idProduct;
            this.productName = productName;
        }

        public Purchases()
        {

        }
    }
}
