//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsDataBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mammal : IAnimal
    {
        public int animalId { get; set; }
        public string animalClass { get; set; }
        public string animalSquad { get; set; }
        public string animalFamily { get; set; }
        public string animalGenus { get; set; }
        public string animalSpecies { get; set; }

        /// <summary>
        /// Для создания новой записи
        /// </summary>
        /// <param name="animalClass"></param>
        /// <param name="animalSquad"></param>
        /// <param name="animalFamily"></param>
        /// <param name="animalGenus"></param>
        /// <param name="animalSpecies"></param>
        public Mammal(string animalClass,
                 string animalSquad,
                 string animalFamily,
                 string animalGenus,
                 string animalSpecies)
        {
            this.animalClass = animalClass;
            this.animalSquad = animalSquad;
            this.animalFamily = animalFamily;
            this.animalGenus = animalGenus;
            this.animalSpecies = animalSpecies;
        }
        /// <summary>
        /// Для загрузки данных из БД
        /// </summary>
        public Mammal()
        {

        }
    }
}
